src/components/SelectFacilityModal.vue

Closes #19
Added space at the bottom of the selectFacilityModal so as to give space for the favIcon to avoid overlapping of content.

Improved: bottom padding in the selectFacilityModal for favIcon (#19)

---

src/components/SelectFacilityModal.vue
src/store/modules/util/actions.ts
src/views/UserDetails.vue
src/views/UserQuickSetup.vue

Closes #67
Implemented logic such that user with facility login can only select one facility to be associated with at a time.
Added filter to exclude virtual facilities while fetching facilites for facility login user.

Implemented: single facility selection for facility login(#67)

---

src/views/UserDetails.vue

Closes #73
Fixed issue when enabled user is showing disabled in UI.

Fixed: statusId for user showing opposite for disabled user in UI (#73)

---

src/views/FindUsers.vue

Closes #60
Improved visibility of current user on top of find users page.
- Added badge "Your user" for current user
- Displaying current user in card.

Improved: visibility of current user on top of find users page (#60)

---

src/components/SelectFacilityModal.vue
src/services/UserService.ts
src/views/UserDetails.vue

Closes #64
Implemented services and logic for associating user with facility as a facility login.

Implemented: services and logic for associating user with facility as a facility login (#64)

---

src/views/UserDetails.vue
src/views/UserQuickSetup.vue

Closes #88
Added eye toggle in password input to show and hide password on toggle.

Implemented: eye toggle in password to show and hide password (#88)

---

src/views/UserDetails.vue

Closes #118
Fixed security group selector not showing up due to json parsing error in excludedGroups.

Fixed: excludedSecurityGroups not parsing due to type conversion (#118)

---

src/store/modules/user/actions.ts

Closes #117
Added partyId as first entry in fieldList for fetching users since the api is returning the count of the records for first field.

Improved: fieldList for fetching users for getting correct count as response (#117)

---

src/views/CreateSecurityGroup.vue

Closes #135
On succesfull creation of security group, checked for updated association so as to avoid showing last visited security groups permissions on add permissions page.

Fixed: last visited groups permissions showing checked for newly created security group (#135)

---

src/components/EditSecurityGroupModal.vue
src/components/PermissionItems.vue
src/store/modules/permission/actions.ts
src/store/modules/permission/getters.ts
src/store/modules/permission/index.ts

Closes #150
Displayed permission description in permission card instead of showing group description.
Before
After

Fixed: code to show permission description instead of showing of group (#150)

---

src/store/modules/permission/actions.ts
src/store/modules/permission/getters.ts
src/views/Permissions.vue

Closes #129
Fixed the state type returning from the getters groups with 0 associated permissions. This wrong type prevents users to update state on permission association for new security group.

Fixed: state not updating on permission association for new security group (#129)

---

src/components/PermissionItems.vue
src/views/Permissions.vue

Closes #132
Currently the updateQuery is called on enter key hit. Which results in query to persist on group change if enter key is not hit. Because component is not rendered again on group change.
To fix updated the code to call updateQuery function on the key input.

Fixed: querystring persist on searchbar on group change if not updated in state by keyEnter event (#132)

---

src/views/CreateSecurityGroup.vue

Related issue  #115 
After the creation of security group, when we edit its name then internal ID won't gets affected/changed.

Improved: code by avoiding the change in internalId when group name is renamed(#115)

---

src/views/Permissions.vue

Related Issue #134
Improved csv download logic for permissions such as --
- Download all groups permissions when no security group is selected.
- Show alert if a group is selected but no permissions are associated with that group.

Improved: conditions to show alert only if a group is selected and no permission associated (#134)

---

src/views/Settings.vue

Closes #
Fixed user image loading issue in user-management settins page due to wrong image url being sent to src.

Fixed: user image not loading on userProfile card due to wrong image url

---

src/services/UserService.ts
src/store/modules/user/actions.ts
src/views/UserDetails.vue

Related Issue #172
- Removed unnecessary toast getting displayed on going to details page from created by user tab.
- Removed duplicate toast getting displayed on updating favorites product store.

Fixed: duplicate toast on updating product store and unnecessary toast when redirecting using created by user (#172)

---

CONTRIBUTING.md
capacitor.config.json
ionic.config.json
package-lock.json
package.json

#191 
Changed the app name in all the configurations files in user-management application.

Updated: the app name in config files(#191)

---

src/views/UserDetails.vue

#201 
- Disabled the selection of the Favorite ProductStore on UI when user is not fully authentiacted.

Improved: in fav productStore and shopifyShop, added check for valid userLoginId(#201)

---

src/components/FilterMenu.vue
src/components/PermissionItems.vue
src/components/ProductStoreActionsPopover.vue
src/components/SelectFacilityModal.vue
src/components/SelectProductStoreModal.vue
src/views/CreateUser.vue
src/views/Permissions.vue
src/views/UserDetails.vue
src/views/UserQuickSetup.vue
src/views/Users.vue

#199 
- When no username is available for a security group or product store, the respective field will display the associated ID.

Improved: Display IDs for Security Group and Product Store(#199)

---

src/views/Users.vue

Related Issue #84 
In ionic 7.6.0, an issue is fixed for triggering infinite scroll on quickly scrolling or items have not filled the complete page. This resulted in the issue of infinite scroll when used with search. So added a key on infinite scroll to re-render the same when keyword is changed

Fixed: infinite scroll issue when used with searchbar(#84)

---

src/views/Users.vue

Related Issue #84 
Removed the logic to re-render the infinite-scroll on queryString check that has been added in the previous PR.
Added a variable to check whether the scrolling can be enabled or not whenever users lands on the list page. For this, we have determined the height of the content part scroll and infiniteScroll component and if the height is less than 0 then only enabling the infinite-scroll component
Removed disabled as once the infiniteScroll is disabled it does not gets enabled again, hence removed the disabled property and instead used v-show to enable/disable infinite scroll.

Improved: the logic for fixing infinite scroll(#84)

---

src/store/modules/user/actions.ts

#211 
when api fails while loading more users, the previous loaded content will not be removed and empty state will also not get displayed.

Fixed: empty state will not show on Api fail(#211)

---

src/components/ResetPasswordModal.vue

#198
When an admin or super user resets a user's password, the field where the new password is entered will be empty to avoid showing any sensitive information like the old password.

Fixed: new password field will not be autofilled(#198)

---

src/locales/en.json
src/views/CreateUser.vue
src/views/UserConfirmation.vue

#215 
After successfully creating a new user, a toast message will be displayed on the user interface to inform the user about the success of the operation.

Improved: added toast after successfully creating a new user(#215)

---

src/views/UserDetails.vue

#219 
Implemented feature button disabling based on user permissions to prevent unauthorized access.

Fixed: Disable feature buttons for unauthorized users(#219)

---

src/locales/en.json
src/views/UserDetails.vue

#231 
- Chnaged the incorrect Helper Text on User Details Page After Creating a New User.
- removed the extra line on the in the login details section around helper-text.
[
](url)

Improved: the helper-text on User Details Page(#231)

---

src/router/index.ts

#233 
- Fixed the redirection of Permissions URL to blank page or settings page.
- To fix the incorrect redirection issue, I can update the `redirectToPath` in my `beforeEach` guard to use `/tabs/settings` instead of `/settings`.
- when the user navigates from `/tabs/permissions` to `/settings`, they will be redirected to `/tabs/settings` instead

Fixed: Permissions tab URL will redirect to valid route(#233)

---

src/router/index.ts

#233 
- Improved the logic of `router.beforeEach`.
- The `router.beforeEach` function checks if the user has permission to access a route. If not, it shows a toast message and redirects the user based on the previous route. If the previous route was the login page or the root path, the user is redirected to the settings page; otherwise, they are redirected back to the previous route

Improved: the logic of router.beforeEach and  fix the toast issue while navigating(#233)

---

src/views/Users.vue

As we fetch the current user information on initial load of the page, but on infinite scroll the same information is fetched again, thus making redundant call. Added a check to not fetch current user information when scrolling on the page.

Fixed: redundant api calls are made when fetching current user information on infinite scroll

---

src/components/PermissionItems.vue

#136
Added click event on the whole permission card instead of just on checkbox.

Improved: made whole permission item card clickable (#136)

---

src/views/Permissions.vue

#266 
- Previously, the `UserLoginAndSecurityGroup` entity was showing users who were not `APPLICATION_USER`.
- I changed it to `PartyAndUserLoginSecurityGroupDetails` and added a filter for `roleTypeId: APPLICATION_USER`, which now only retrieves users with the `APPLICATION_USER` role.

Fixed:  linked user count matches the Users page after clicking the link(#266)

---

src/locales/en.json
src/router/index.ts

#233 
- In case when the user doesn't have permission for the permissions page, updated the toast message to show:
`The requested page was not available to your user. Please contact your administrator to update your permissions.`

Improved: Updated the toast message while navigating to permissions page(#233)

---

src/store/modules/user/actions.ts
src/views/UserDetails.vue

#253
- Refetching the user picker role relationship details on show as picker toggle change to have updated picker relationship details.

Fixed: show as picker not toggling off immediately after toggling on. (#253)

---

src/locales/en.json
src/views/UserQuickSetup.vue

#252
- Changed the label for button to open select facilities modal.
- Improved selected facilities visibility and management on quick user setup.
Before
After

Improved: UI for the select facilities option in the quick user setup page (#252)

---

src/components/ProductStoreActionsPopover.vue
src/locales/en.json
src/views/UserDetails.vue

#240
Improved ui of the product store selection for the consistency with the security group selection.
Before
After

Improved: UI for the product store management (#240)

---

src/views/Permissions.vue

#265 
- The download will now show the permissions description in the column instead of the security group description.
- Additionally, the column name has been changed to `Association date` instead of `Created date`.

Fixed: added permissions description column instead of the security group description(#265)

---

src/views/UserDetails.vue

#279 
- Disabled the `Add Security Group` button for newly created users who do not have a `userLoginId`.
- Admins/Super users will not be able to assign a security group to newly created users, as the button appears disabled.

Improved: Adding secuity group is disabled for newly created user without useLoginID(#279)

---

src/components/ProductStoreActionsPopover.vue

#240
Added a check for disabling button to redirect to store detail if no omsRedirection url present.

Improved: disabling button for redirecting to store if no omsRedirection url is not present (#240)

---

src/components/SecurityGroupActionsPopover.vue
src/views/UserDetails.vue

#278 
- Upon changing the security group, permissions to access the Fulfillment section are re-fetched.
- The Fulfillment section is updated after the security group is removed via the popover's remove button, accessed from the ellipse icon.

Fixed: Fulfillment section updated after removing securityGroup from the ellipse button (#278)

---

src/components/PermissionItems.vue
src/store/modules/permission/getters.ts

#277 
Removed the check for HIDDEN group from the template part and removed the HIDDEN group records from the getter which was returning the permissions to be displayed on UI

Fixed: issue of empty state not being displayed when searching for a permission whose type is HIDDEN(#277)

---

src/components/UserSecurityGroupAssocHistoryModal.vue
src/locales/en.json

#295 
- Previously, only expired security groups that were associated with the user were displayed in the modal.  
- Now, we also show the currently active security groups at the top of the list, with a date range from the start date to the `current` text.

Improved: Displayed current security group details in the Permission History modal (#295)

---

src/views/UserQuickSetup.vue

#326 
- After toggling the "Require password reset on login" option, the requirePasswordChange value is passed as true.

Fixed: "Require password reset on login" toggle change (#326)

---

src/views/UserDetails.vue

#318 
#
Now user does not require userLogin Id to disable a particular user.

Improved: user does not require userLogin id to disable user.(#318)

---

src/services/UserService.ts
src/views/UserQuickSetup.vue

#336 
- Now, when we create a new user and the user already exists, the correct toast message will be shown during quick setup.

Fixed: Correct toast message is now shown when a user already exists during quick setup (#336)

---

src/locales/en.json
src/views/UserDetails.vue

#319 
Solved these two tasks given in issue-
1. If no user login is available for someone then displaying message under the disabled button.
2. The changes ensure that the history is fetched when the page loads, stored in a local variable, and used for conditional rendering  the UserSecurityGroupAssocHistoryModal.
[Screencast from 26-03-25 08:08:34 PM IST.webm](https://github.com/user-attachments/assets/003bd309-52e7-468d-b402-49e12e686c9f)

Displaying info message when no user login available and hiding the history modal icon if user was present in at least one security group. (#319)

---

src/services/UserService.ts
src/views/CreateUser.vue
src/views/UserDetails.vue
src/views/UserQuickSetup.vue

Role type for newly created user is changed to WAREHOUSE_PICKER from WAREHOUSE_PICKER
#347
When facilities are added to users, the secas working for employee indexing were set to take WAREHOUSE_PICKER as user's roleTypeId, due to which indexing wasn't being performed

Fixed: Role type for newly created user is changed to WAREHOUSE_PICKER from WAREHOUSE_MANAGER, (#347)

---

src/views/UserDetails.vue

Option To Add Facility Association When Showing User
#340 : Option To Add Facility Association When Showing User As Picker
- When creating a user as picker, option to associate with facility should also be provided, so as to avoid confusion in case user has STOREFULFILLMENT_ADMIN permission.
- As we only show associated picker in fulfillment and user with STOREFULFILLMENT_ADMIN permission gives the impression that user will picker in all facilities.
- Picker Association on users app should reflect on fulfillment app.

Fixed : Option To Add Facility Association When Showing User #340
