hotwax/users

- .firebaserc
> Update .firebaserc for deployement

- src/services/UserService.ts
- src/store/modules/user/actions.ts
- src/utils/index.ts
- src/views/CreateUser.vue
- src/views/FindUsers.vue
- src/views/UserConfirmation.vue
- src/views/UserDetails.vue
- src/views/UserQuickSetup.vue
Closes #
Improved: Associated party to the facility on party creation for the store login user.
> Improved: Associated party to the facility on party creation for the store login user.

- src/services/UserService.ts
Closes #
Fixed: Ensured party role before associated party to facility and product store.
> Fixed: Ensured party role before associated party to facility and product store.

- package-lock.json
- package.json
> Updated: app theme version

- src/components/ProductStoreActionsPopover.vue
- src/locales/en.json
- src/store/modules/user/actions.ts
- src/store/modules/util/actions.ts
- src/views/FindUsers.vue
- src/views/UserDetails.vue
Closes #
Improved: Status filters and text.
> Improved: Status filters and text

- package-lock.json
- package.json
> Updated: App version for major release (1.0.0).

- src/services/UserService.ts
- src/views/CreateUser.vue
- src/views/UserDetails.vue
- src/views/UserQuickSetup.vue
Closes #
Miscellaneous fixes in users app.
> Miscellaneous fixes in users app.

- src/views/UserConfirmation.vue
- src/views/UserQuickSetup.vue
…
Closes #
Fixed: Finish and Create User functionality and back button functionality.
> Fixed: Finish and Create User functionality and back button functionality.

- src/views/UserDetails.vue
Closes #32
Fixed: User detail was not updated after creation new user.
> Fixed: User detail was not updated after creation new user.

- src/views/CreateUser.vue
- src/views/UserQuickSetup.vue
Closes #
Removed: clear option from input fields.
> Removed: clear option from input fields.

- package-lock.json
- package.json
Closes #
Updated: App version for fix release (1.0.2).
> Updated: App version for fix release (1.0.2).

- package-lock.json
- package.json
> Improved: app version in package and lock file for patch release(v1.0.3)

- src/services/UserService.ts
- src/store/modules/user/actions.ts
- src/views/UserDetails.vue
…
Closes #
Fixed: Create/updated party relationship while assigning WAREHOUSE_PICKER role instead of just assigning role.
> Fixed: Create/updated party relationship while assigning WAREHOUSE_PICKER role instead of just assigning role.

- src/views/CreateUser.vue
Closes #
Improved: Auto focused first name field in Create User form.
> Improved: Auto focused first name field in Create User form.

- src/components/FilterMenu.vue
> Implemented: support for disabled user filter in mobile view

- src/views/UserDetails.vue
Closes #71
Improved code to show a emoji if user is created by system and also redirect it to an external video on youtube.
> Improved: code to handle users created by system (#71)

- src/locales/en.json
- src/views/UserDetails.vue
Closes #70
Implemented toast for missing fields in user login details.
> Implemented: toast for missing fields in user login details (#70)

- src/views/UserDetails.vue
Closes #
Improved indentation of user-details page.
> Improved: indentation of user-details page inside main

- package-lock.json
- package.json
Closes #
Updated: app version for the minor release (1.3.0).
> Updated: app version for the minor release (1.3.0).

- src/views/UserDetails.vue
Closes #71
Fixed link not opening in new tab for user created by not found.
> Fixed: opening link in new tab when user created not found(#71)

- src/views/UserDetails.vue
- src/views/UserQuickSetup.vue
Closes #90
Implemented integration allowing users to create user with integration security group.
> Implemented: integration template to quick setup (#90)

- src/views/FindUsers.vue
> Improved: Current user info displayed on first load irrespective of whether other users information is fetched or not(#82)

- package-lock.json
- package.json
> Updated: app version for minor release(1.4.0)

- src/components/ContactActionsPopover.vue
- src/views/UserDetails.vue
Closes #120
Fixed the external id updation issue by passing as payload required field for the api such as firstName and groupName
> Improved: logic to update external id by passing required fields (#120)

- src/services/UserService.ts
- src/views/UserQuickSetup.vue
Closes #124
Fixed facility login creation failure due to missing facilityId in quick user setup.
> Fixed: facility login creation failed due to missing facilityId (#124)

- src/views/Permissions.vue
Closes #113
Changed the csv file name format to be downloaded in following format: 
HotWaxSecurityGroupExport_YYYY_MM_DD_HH:MM
> Improved: file name format for permissions csv (#113)

- src/store/modules/user/actions.ts
Closes #107
Improved login action to redirect user to details page if redirected from facilities if login credentials and partyId are passed as a query.
> Improved: login action to redirect user to details page if redirect from facilities (#107)

- package-lock.json
- package.json
Closes #
Updated: app version for the minor release (1.5.0).
> Updated: app version for the minor release (1.5.0).

- src/views/CreateSecurityGroup.vue
- src/views/Permissions.vue
Closes #132
Improved code to clear query state for permission so as to reset queries on security group change.
> Improved: code to clear query state on changing security group (#132)

- src/store/modules/permission/getters.ts
Closes #128
Added searching on the permissionId too, for the permissions search.
> Improved: added searching on the permissionId for the permissions query (#128)

- src/store/modules/permission/actions.ts
Closes #152
Improved payload to avoid fetching permission under hidden group.
> Improved: added filter to avoid fetching permissions undetr hidden group (#152)

- package-lock.json
- package.json
> Updated: app version for the patch release (v1.5.2)

- package-lock.json
- package.json
> Updated: app version for the minor release (v1.6.0)

- src/views/CreateSecurityGroup.vue
#127 
Updated the code to handle the case of duplicate internal ID and showing the toast message for the same on the UI.
> Fixed: Toast message displayed for duplicate Internal ID(#127)

- src/views/UserDetails.vue
#167 
Add check for the user who don't have the permissions to add Product store.
> Fixed: Disable the adding of product store for CSR(#167)

- src/views/CreateSecurityGroup.vue
> Fixed: issue in creating the groupId when id left empty(#175)

- package-lock.json
- package.json
Closes #
Updated: app version for the minor release (v1.7.0).
> Updated: app version for the minor release (v1.7.0).

- src/components/PermissionItems.vue
#188
Fixed the bug of multiple api call during adding and removing the permissions of the user. Now it will only have one api call for particular operations.
> FIxed: the multiple api calls for permissions (#188)

- src/locales/en.json
- src/views/UserDetails.vue
#185 
- Added the image validation on the user details page.
- Users should not be able to upload files with invalid formats, if it does than will show a toast.
- A toast is displaying on uploading a image.
> Improved: Added the functionality to validate image and show toast(#185)

- package-lock.json
- package.json
Closes #
Updated: app version for minor release (v1.8.0).
> Updated: app version for minor release (v1.8.0).

- manifest.json
- package.json
- public/index.html
#191 
Changed the app name from manifest.json , index.html and description of package.json file.
> Upadated: app name from different files(#191)

- src/components/PermissionItems.vue
- src/store/modules/permission/actions.ts
Related Issue #209
Added the others category and hide the Hidden category.
> Improved: code to add Others category and hide Hidden category (#209)

- package-lock.json
- package.json
Closes #
Updated: app version for minor release (v1.9.0)
> Updated: app version for minor release (v1.9.0)

- package-lock.json
- package.json
Closes #
Updated: app version for patch release (v1.9.1).
> Updated: app version for patch release (v1.9.1).

- src/main.ts
#84 
- Added a entry in `main` file to fix html tags not working in the translations.
> Fixed: html tags not working in the translations (#84)

- package-lock.json
- package.json
Closes #
Updated: app version for minor release (v1.10.0).
> Updated: app version for minor release (v1.10.0).

- src/components/PermissionItems.vue
Related Issue #227
Fixed checkbox getting checked even if api failed.
> Fixed: checkbox getting checked even if api is failed (#227)

- package-lock.json
- package.json
> Updated: app version for the patch release (v1.10.1)

- src/store/modules/permission/actions.ts
Closes #
Added filterByDate in the payload for fetching the permissions by classifications
> Improved: added filterByDate in payload for fetching permissions by classifications

- package-lock.json
- package.json
> Updated: app version for the patch release (v1.10.2)

- src/store/modules/user/actions.ts
#149
Made improvements to handle the state of usersList and ensured that users are correctly concatenated
> Fixed: state not updating in case of no record for fetching users (#149)

- src/components/PermissionItems.vue
#260
Improved code to replace the checkbox with spinner until the api call for updating permission association with the security group completes.
> Improved: displayed spinner in-place of checkbox in permission items while the item associtation is updating (#260)

- package-lock.json
- package.json
> Updated: app version for minor release v1.11.0

- src/services/UserService.ts
- src/store/modules/user/actions.ts
- src/views/UserDetails.vue
#292
Managing show as picker setting of an user using the partyRole instead of party relationship.
**Note:** The setting status might not reflect directly in our other app where we are fetching using the Solr, due to indexing issue.
> Improved: migrated the party picker logic from party relationship to party role (#292)

- package-lock.json
- package.json
> Updated: app version for patch release v1.11.1

- firebase.json
#288 [104](https://github.com/hotwax/launchpad/issues/104)
added: security headers in firebase.json in hotwax/users
> added: security headers - hotwax/users

- package-lock.json
- package.json
> Updated: app version for the minor release v1.12.0

- src/components/EditSecurityGroupModal.vue
> Fixed: Handle long descriptions in security group update.(#285)

- src/store/modules/user/getters.ts
#296 
#
Now newly created User are visible on the List Page.
> Fixed: Newly Created Users Not Visible on List Page Unless Searched.(#296)

- src/App.vue
- src/locales/en.json
- src/store/modules/user/actions.ts
https://github.com/hotwax/dxp-components/issues/321
> Fixed: refactored loader presentation logic to support custom messages and backdrop dismissal default false (hotwax/dxp-components#321)

- src/services/UserService.ts
#329
Instead of creating party relationship, creating party role while user creation with template having picker as role.
> Improved: creating partyRole instead of partyRelationship while user creation with picker role (#329)

- package-lock.json
- package.json
> Updated: app version for minor release v1.13.0

- src/store/modules/util/actions.ts
> Fixed: issue of facilities not being displayed in the facilities association modal if the total facilities in the system exceeds 100(#341)

- package-lock.json
- package.json
> Improved: app version in package and lock file for patch release(v1.13.2)

- package-lock.json
- package.json
> Updated: app version for patch release v1.14.1
